In [1]:
import pandas as pd
import numpy as np

In [2]:
Survey_2014 = pd.read_csv("OSMI Tech Mental Health Surveys/2014 OSMI Survey.csv")

In [8]:
#Automating reading in of Survey Data to a list of dataframes
Surveys = []
for num in range(2016, 2023):
    Surveys.append(pd.read_csv(f"OSMI Tech Mental Health Surveys/{num} OSMI Survey.csv"))

In [110]:
#Choosing a subset of column survey questions to keep 
columns_keep = ['How many employees does your company or organization have?', 
                'Is your employer primarily a tech company/organization?',
               'Does your employer provide mental health benefits as part of healthcare coverage?', 
                'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
               'Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?',
               'Do you believe your productivity is ever affected by a mental health issue?',
               'If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?',
                'Do you currently have a mental health disorder?',
               'What is your age?',
                'What is your gender?',
                'What country do you live in?',
                'year'
               ]

In [ ]:
#columns to change:

#Surveys[0] : 'Does your employer offer resources to learn more about mental health concerns and options for seeking help?'
#Surveys[0] : 'Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?'

#Surveys[1] : 'Does your employer provide mental health benefits\xa0as part of healthcare coverage?' *


#Surveys[6] : 'Do you *currently* have a mental health disorder?'
#Surveys[5] : 'Do you *currently* have a mental health disorder?'
#Surveys[4] : 'Do you *currently* have a mental health disorder?'
#Surveys[3] : 'Do you *currently* have a mental health disorder?'

#Surveys[1] : 'What country do you <strong>live</strong> in?'
#Surveys[2] : 'What country do you <strong>live</strong> in?'
#Surveys[3] : 'What country do you *live* in?'
#Surveys[4] : 'What country do you *live* in?'
#Surveys[5] : 'What country do you *live* in?'
#Surveys[6] : 'What country do you *live* in?'

In [12]:
#Replacing incorrect column names in survey1
Surveys[1].rename(columns={'Does your employer provide mental health benefits\xa0as part of healthcare coverage?' : 'Does your employer provide mental health benefits as part of healthcare coverage?',
                              'What country do you <strong>live</strong> in?' : 'What country do you live in?' }, inplace=True)

In [15]:
Surveys[2].rename(columns={'What country do you <strong>live</strong> in?' : 'What country do you live in?' },inplace=True)

In [53]:
Surveys[0].rename(columns={'Does your employer offer resources to learn more about mental health concerns and options for seeking help?' : 
                           'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
                           'Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?':
                            'Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?'},inplace=True)

In [13]:
#Automatically replacing incorrect column names 
for num in range(3,7):
    Surveys[num].rename(columns={'Do you *currently* have a mental health disorder?' : 'Do you currently have a mental health disorder?',
                                    'What country do you *live* in?': 'What country do you live in?' }, inplace=True)

In [64]:
#Adding a Year column to every Survey
num = 2016
for frame in Surveys:
    frame["year"] = num
    num += 1

Survey_2014["year"] = 2014

In [68]:
#validating year column
Surveys[2]["year"]

0      2018
1      2018
2      2018
3      2018
4      2018
       ...
412    2018
413    2018
414    2018
415    2018
416    2018
Name: year, Length: 417, dtype: int64

In [70]:
#Automatically Reducing columns/survey questions to questions list for every years survey
Surveys_short = []
for survey in Surveys:
    Surveys_short.append(survey[columns_keep])

In [71]:
#Appending Surveys into a single Dataframe
Surveys_joined = pd.concat(Surveys_short)

In [72]:
Surveys_joined

,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Does your employer provide mental health benefits as part of healthcare coverage?,Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",Do you currently have a mental health disorder?,What is your age?,What is your gender?,What country do you live in?,year
0,26-100,1.0,Not eligible for coverage / N/A,No,Yes,NaN,NaN,No,39.0,Male,United Kingdom,2016
1,6-25,1.0,No,Yes,Yes,NaN,NaN,Yes,29.0,male,United States of America,2016
2,6-25,1.0,No,No,Maybe,NaN,NaN,No,38.0,Male,United Kingdom,2016
3,NaN,NaN,NaN,NaN,NaN,Yes,1-25%,Yes,43.0,male,United Kingdom,2016
4,6-25,0.0,Yes,No,No,NaN,NaN,Yes,43.0,Female,United States of America,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
159,More than 1000,1.0,I don't know,Yes,Maybe,NaN,NaN,No,31.0,female,Poland,2022
160,26-100,1.0,Yes,Yes,No,NaN,NaN,Don't Know,40.0,M,Australia,2022
161,26-100,1.0,I don't know,Yes,Yes,NaN,NaN,Possibly,23.0,NaN,United States of America,2022
162,NaN,NaN,NaN,NaN,NaN,Yes,26-50%,Possibly,21.0,Female,Kazakhstan,2022
163,6-25,1.0,No,No,No,NaN,NaN,Yes,32.0,female,Russia,2022

In [75]:
#Saving current progress
Surveys_joined.to_csv("full_survey.csv")

In [73]:
Surveys_joined['year'].isna().any()

False

In [74]:
Surveys_joined['year'].value_counts()

year
2016    1433
2017     756
2018     417
2019     352
2020     180
2022     164
2021     131
Name: count, dtype: int64

In [77]:
Surveys_joined['What country do you live in?'].isna().sum()

2

In [85]:
#Dropping missing values
Surveys_joined.dropna(subset=['What country do you live in?'],inplace=True)
Surveys_joined['What country do you live in?'].isna().sum()

0

In [88]:
#Checking values in country column
Surveys_joined['What country do you live in?'].value_counts().index.to_list()

['United States of America',
 'United Kingdom',
 'Canada',
 'Germany',
 'India',
 'Netherlands',
 'Australia',
 'Brazil',
 'France',
 'Spain',
 'Ireland',
 'Sweden',
 'Portugal',
 'Switzerland',
 'Poland',
 'Italy',
 'Russia',
 'New Zealand',
 'South Africa',
 'Belgium',
 'Finland',
 'Norway',
 'Indonesia',
 'Austria',
 'Bulgaria',
 'Mexico',
 'Japan',
 'Pakistan',
 'Romania',
 'Turkey',
 'Denmark',
 'Colombia',
 'Israel',
 'Slovenia',
 'Serbia',
 'Macedonia',
 'Argentina',
 'Bangladesh',
 'Greece',
 'Estonia',
 'Czech Republic',
 'Ukraine',
 'Chile',
 'Iceland',
 'Philippines',
 'Taiwan',
 'Hungary',
 'Lithuania',
 'Bosnia and Herzegovina',
 'Afghanistan',
 'Vietnam',
 'China',
 'Belarus',
 'Sri Lanka',
 'Mongolia',
 'Hong Kong',
 'Kenya',
 'Nigeria',
 'Uruguay',
 'Croatia',
 'Jordan',
 'Algeria',
 'Other',
 'Slovakia',
 'Singapore',
 'Ecuador',
 'Aruba',
 'Panama',
 'Peru',
 'Somalia',
 'Sao Tome and Principe',
 'Albania',
 'Guatemala',
 'Malaysia',
 'Egypt',
 'Iran',
 'Venezuela',
 'Cameroon',
 'Ghana',
 'Georgia',
 'Brunei',
 'Costa Rica',
 'Ethiopia',
 'Saudi Arabia',
 'Mauritius',
 'Latvia',
 'Kazakhstan']

In [90]:
Surveys_joined['What is your gender?'].isna().sum()

32

In [91]:
#dropping missing values
Surveys_joined.dropna(subset=['What is your gender?'],inplace=True)
Surveys_joined['What is your gender?'].isna().sum()

0

In [96]:
#removing leading spaces from gender column
Surveys_joined['What is your gender?'] = Surveys_joined['What is your gender?'].str.strip()

In [97]:
Surveys_joined['What is your gender?'].value_counts().index.to_list()

['Male',
 'male',
 'Female',
 'female',
 'M',
 'm',
 'F',
 'f',
 'Woman',
 'woman',
 'Nonbinary',
 'Man',
 'man',
 'cis male',
 'non-binary',
 'Cis Male',
 'Non-binary',
 'Female (cis)',
 'Cis-male',
 'MALE',
 'Genderqueer',
 'Cis male',
 'Male (cis)',
 'Agender',
 'Genderfluid',
 'Non binary',
 'Trans man',
 'Masculine',
 'dude',
 'agender',
 'Queer',
 'mail',
 'FEMALE',
 'Other',
 'Cis female',
 'Trans non-binary/genderfluid',
 'none',
 'Demiguy',
 'genderfluid',
 'Trans woman',
 'Cisgendered woman',
 'Cis-Female',
 'Female (cisgender)',
 'Cis woman',
 'Female/gender non-binary.',
 'non binary',
 'b',
 'male/he/him',
 'transgender',
 'afab non-binary',
 'homem cis',
 'Male (or female, or both)',
 '*shrug emoji* (F)',
 'cis-het male',
 'I identify as female',
 'Malel',
 'Non-binary/Agender',
 'male, born with xy chromosoms',
 'Ostensibly Male',
 'Female, cis-gendered',
 'Transfeminine',
 'trans woman',
 'Trans female',
 'She/her/they/them',
 'Cisgender male',
 'Questioning',
 'CIS Male',
 'I am a Wookie',
 'Non-binary and gender fluid',
 'masculino',
 '43',
 'femmina',
 'Agender trans woman',
 'Femile',
 'cis woman',
 'rr',
 'I have a penis',
 'Female-ish',
 'Female-identified',
 'Make',
 'female, she/her',
 'Cishet male',
 'mostly male',
 'Identify as male',
 'cisgender male',
 'Let\'s keep it simple and say "male"',
 'gender non-conforming woman',
 'MAle',
 'Nonbinary/femme',
 'NB',
 'cisgender female',
 'SWM',
 '\\-',
 'Male, cis',
 'F, cisgender',
 'Sex is male',
 'fem',
 'Male/genderqueer',
 'M|',
 "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take?",
 'Fluid',
 'Dude',
 'mtf',
 'genderqueer woman',
 'Malr',
 'Enby',
 'Human',
 'genderqueer',
 'none of your business',
 'Cisgender Female',
 'Female (props for making this a freeform field, though)',
 'nb masculine',
 'male 9:1 female, roughly',
 'Androgynous',
 'Male.',
 'female/woman',
 'Female or Multi-Gender Femme',
 'Other/Transfeminine',
 'Genderfluid (born female)',
 'Transitioned, M2F',
 'fm',
 'Female assigned at birth',
 'Bigender',
 'I identify as female.',
 'human',
 'Unicorn',
 'nonbinary',
 "male (hey this is the tech industry you're talking about)",
 'cis female',
 'cis-Female',
 'Genderqueer/non-binary',
 'Genderqueer demigirl',
 'Contextual',
 'Woman-identified',
 'female (cisgender)',
 'sometimes',
 'Male-ish',
 'Agender/genderfluid',
 'My sex is female.',
 'God King of the Valajar',
 'female (cis)',
 'uhhhhhhhhh fem genderqueer?',
 'Male (trans, FtM)',
 'femail',
 'femalw',
 'cis hetero male',
 'male/androgynous',
 'Mail',
 'cis-male',
 'Transgender woman',
 'AFAB',
 'cis man',
 'female-bodied; no feelings about gender',
 'Genderflux demi-girl',
 'cisdude',
 'Cis-woman',
 'varón']

In [99]:
#dictionary to replace erronious and misspelled values with Male
Male_dict = { 'male': 'Male', 'M': 'Male','m': 'Male', 'Man': 'Male', 'man': 'Male', 'cis male': 'Male', 'Cis Male': 'Male',
               'Cis-male': 'Male', 'MALE': 'Male', 'Cis male': 'Male', 'Male (cis)': 'Male', 'Masculine': 'Male', 'dude': 'Male',
               'mail': 'Male', 'b': 'Male', 'male/he/him': 'Male', 'homem cis': 'Male', 'cis-het male': 'Male', 'Malel': 'Male',
               'Ostensibly Male': 'Male', 'male, born with xy chromosoms': 'Male',
               'Cisgender male': 'Male', 'CIS Male': 'Male', 'I am a Wookie': 'Male', 'masculino': 'Male', '43': 'Male',
             'I have a penis': 'Male', 'Cishet male': 'Male', 'mostly male': 'Male', 'Identify as male': 'Male', 'cisgender male': 'Male',
             'Let\'s keep it simple and say "male"': 'Male', 'M|': 'Male', 
             "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take?": 'Male',
             'MAle': 'Male', 'Male, cis': 'Male', 'Sex is male': 'Male', 'Dude': 'Male', 'Malr': 'Male',
             'male 9:1 female, roughly': 'Male', 'Male.': 'Male', "male (hey this is the tech industry you're talking about)": 'Male',
             'God King of the Valajar': 'Male', 'cis hetero male': 'Male', 'male/androgynous': 'Male', 'Mail': 'Male', 'cis-male': 'Male', 'cis man': 'Male', 
             'cisdude': 'Male', 'varón': 'Male'}

In [100]:
#replacing values using defined dictionary
Surveys_joined['What is your gender?'] = Surveys_joined['What is your gender?'].replace(Male_dict)

In [101]:
Surveys_joined['What is your gender?'].value_counts().index.to_list()

['Male',
 'Female',
 'female',
 'F',
 'f',
 'Woman',
 'woman',
 'Nonbinary',
 'non-binary',
 'Non-binary',
 'Agender',
 'Genderqueer',
 'Genderfluid',
 'Female (cis)',
 'Queer',
 'Trans man',
 'agender',
 'Other',
 'FEMALE',
 'Cis female',
 'Non binary',
 'I identify as female',
 'F, cisgender',
 'Cisgendered woman',
 'Female-ish',
 'Cis-Female',
 'Female (cisgender)',
 'Cis woman',
 'Female/gender non-binary.',
 'genderfluid',
 'non binary',
 'transgender',
 '\\-',
 'trans woman',
 'Male (or female, or both)',
 'Transfeminine',
 '*shrug emoji* (F)',
 'Trans woman',
 'cisgender female',
 'Demiguy',
 'cis woman',
 'Non-binary/Agender',
 'afab non-binary',
 'female, she/her',
 'Femile',
 'Non-binary and gender fluid',
 'Trans non-binary/genderfluid',
 'Make',
 'femmina',
 'Agender trans woman',
 'rr',
 'none',
 'Questioning',
 'Female-identified',
 'gender non-conforming woman',
 'Nonbinary/femme',
 'NB',
 'cis female',
 'SWM',
 'She/her/they/them',
 'Trans female',
 'nonbinary',
 'sometimes',
 'cis-Female',
 'Genderqueer/non-binary',
 'Fluid',
 'mtf',
 'genderqueer woman',
 'Enby',
 'Human',
 'genderqueer',
 'none of your business',
 'Cisgender Female',
 'nb masculine',
 'Androgynous',
 'female/woman',
 'Female or Multi-Gender Femme',
 'Other/Transfeminine',
 'Genderfluid (born female)',
 'Transitioned, M2F',
 'fm',
 'Female assigned at birth',
 'Bigender',
 'I identify as female.',
 'Male/genderqueer',
 'fem',
 'human',
 'uhhhhhhhhh fem genderqueer?',
 'Genderqueer demigirl',
 'Contextual',
 'Woman-identified',
 'female (cisgender)',
 'Male-ish',
 'Agender/genderfluid',
 'My sex is female.',
 'female (cis)',
 'femail',
 'Female (props for making this a freeform field, though)',
 'femalw',
 'Transgender woman',
 'AFAB',
 'female-bodied; no feelings about gender',
 'Genderflux demi-girl',
 'Cis-woman',
 'Male (trans, FtM)',
 'Unicorn',
 'Female, cis-gendered']

In [102]:
#Repeating steps above for Female category
Female_dict = { "female" : "Female", "F" : "Female", "f" : "Female", "Woman" : "Female", "woman" : "Female", "Female (cis)" : "Female", "FEMALE" : "Female",
               "Cis female" : "Female", "I identify as female" : "Female", "F, cisgender" : "Female", "Cisgendered woman" : "Female", 
               "Female-ish" : "Female", "Cis-Female" : "Female", "Female (cisgender)" : "Female",
               "Cis woman" : "Female", "*shrug emoji* (F)" : "Female", "cisgender female" : "Female", "cis woman" : "Female", "female, she/her" : "Female",
               "Femile" : "Female", "" : "Female", "femmina" : "Female", "cis female" : "Female", "cis-Female" : "Female", "genderqueer woman" : "Female", 
               "Cisgender Female" : "Female", "female/woman" : "Female", "Female or Multi-Gender Femme" : "Female", "fm" : "Female", "Female assigned at birth" : "Female", 
               "I identify as female." : "Female", "fem" : "Female", "female (cisgender)" : "Female", "My sex is female." : "Female", "female (cis)" : "Female",
               "femail" : "Female", "Female (props for making this a freeform field, though)" : "Female", "femalw" : "Female",
               "female-bodied; no feelings about gender" : "Female", "Cis-woman" : "Female"}

In [103]:
Surveys_joined['What is your gender?'] = Surveys_joined['What is your gender?'].replace(Female_dict)

In [105]:
#Repeating steps above for Non-binary category
mixed_dict = { "Nonbinary" : "Non-binary", "non-binary" : "Non-binary", "Genderfluid" : "Non-binary", "Agender" : "Non-binary",
              "Genderqueer" : "Non-binary", "Other" : "Non-binary", "agender" : "Non-binary", "Non binary" : "Non-binary", "Queer" : "Non-binary",
              "non binary" : "Non-binary", "genderfluid" : "Non-binary", "none" : "Non-binary", "Female/gender non-binary." : "Non-binary",
              "NB" : "Non-binary", "SWM" : "Non-binary", "\\-" : "Non-binary", "Nonbinary/femme" : "Non-binary",
              "gender non-conforming woman" : "Non-binary", "Questioning" : "Non-binary", "rr" : "Non-binary",
              "Trans non-binary/genderfluid" : "Non-binary", "Non-binary and gender fluid" : "Non-binary", "Non-binary/Agender" : "Non-binary",
              "Contextual" : "Non-binary", "nonbinary" : "Non-binary", "Genderqueer/non-binary" : "Non-binary", "Bigender" : "Non-binary",
              "Genderfluid (born female)" : "Non-binary", "Androgynous" : "Non-binary", "nb masculine" : "Non-binary",
              "genderqueer" : "Non-binary", "human" : "Non-binary", "Unicorn" : "Non-binary", "Genderflux demi-girl" : "Non-binary",
              "AFAB" : "Non-binary", "uhhhhhhhhh fem genderqueer?" : "Non-binary", "Agender/genderfluid" : "Non-binary", "Male-ish" : "Non-binary",
             "sometimes" : "Non-binary", "Genderqueer demigirl" : "Non-binary"}

In [106]:
Surveys_joined['What is your gender?'] = Surveys_joined['What is your gender?'].replace(mixed_dict)

In [108]:
#Repeating steps above for trans man and trans woman categories 
Trans_dict = { "Trans man": "Trans-man", "Male (or female, or both)": "Trans-man", "Male (trans, FtM)": "Trans-man", "Male/genderqueer": "Trans-man",
              "Transfeminine": "Trans-woman", "Agender trans woman": "Trans-woman", "Female-identified": "Trans-woman", "Trans female": "Trans-woman",
              "Trans woman": "Trans-woman", "transgender": "Trans-woman", "trans woman": "Trans-woman", "Woman-identified": "Trans-woman",
              "Transgender woman": "Trans-woman", "mtf": "Trans-woman", "Other/Transfeminine": "Trans-woman", "Transitioned, M2F": "Trans-woman",
              }

In [109]:
Surveys_joined['What is your gender?'] = Surveys_joined['What is your gender?'].replace(Trans_dict)

In [111]:
missed = {'none of your business' : "Other", "Human" : "Other", "Enby" : "Non-binary", "Fluid" : "Non-binary", 
         "Demiguy" : "Other", "She/her/they/them" : "Female", "Make" : "Male", "afab non-binary" : "Non-binary", "Female, cis-gendered" : "Female"}

In [112]:
Surveys_joined['What is your gender?'] = Surveys_joined['What is your gender?'].replace(missed)

In [113]:
#Validating gender column reformatting 
Surveys_joined['What is your gender?'].value_counts().index.to_list()

['Male', 'Female', 'Non-binary', 'Trans-woman', 'Trans-man', 'Other']

In [114]:
Surveys_joined.to_csv("full_survey.csv")

In [2]:
Surveys_joined = pd.read_csv("full_survey.csv")

In [13]:
Surveys_joined["What is your age?"].value_counts().index.to_list()

[30.0,
 31.0,
 32.0,
 35.0,
 28.0,
 34.0,
 29.0,
 37.0,
 33.0,
 27.0,
 38.0,
 26.0,
 36.0,
 39.0,
 40.0,
 25.0,
 24.0,
 42.0,
 23.0,
 45.0,
 41.0,
 44.0,
 22.0,
 43.0,
 46.0,
 47.0,
 49.0,
 21.0,
 50.0,
 48.0,
 55.0,
 51.0,
 53.0,
 20.0,
 52.0,
 54.0,
 19.0,
 57.0,
 56.0,
 59.0,
 61.0,
 58.0,
 63.0,
 60.0,
 62.0,
 65.0,
 64.0,
 67.0,
 18.0,
 66.0,
 0.0,
 5.0,
 2.0,
 11.0,
 3.0,
 70.0,
 74.0,
 15.0,
 17.0,
 323.0,
 99.0,
 76.0]

In [15]:
#limiting age column to reasonable values for the context
Surveys_joined = Surveys_joined[(Surveys_joined["What is your age?"] >=15) & (Surveys_joined["What is your age?"] <= 80)]

In [16]:
Surveys_joined["What is your age?"].value_counts().index.to_list()

[30.0,
 31.0,
 32.0,
 35.0,
 28.0,
 34.0,
 29.0,
 37.0,
 33.0,
 27.0,
 38.0,
 26.0,
 36.0,
 39.0,
 40.0,
 25.0,
 24.0,
 42.0,
 45.0,
 23.0,
 41.0,
 44.0,
 22.0,
 43.0,
 46.0,
 47.0,
 21.0,
 49.0,
 50.0,
 48.0,
 55.0,
 51.0,
 53.0,
 52.0,
 20.0,
 54.0,
 19.0,
 57.0,
 56.0,
 61.0,
 59.0,
 63.0,
 58.0,
 60.0,
 62.0,
 65.0,
 64.0,
 66.0,
 18.0,
 67.0,
 17.0,
 15.0,
 74.0,
 70.0,
 76.0]

In [20]:
Surveys_joined.dtypes

Unnamed: 0                                                                                                                               int64
How many employees does your company or organization have?                                                                              object
Is your employer primarily a tech company/organization?                                                                                 object
Does your employer provide mental health benefits as part of healthcare coverage?                                                       object
Does your employer offer resources to learn more about mental health disorders and options for seeking help?                            object
Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?                                             object
Do you believe your productivity is ever affected by a mental health issue?                                                             object
If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?    object
Do you currently have a mental health disorder?                                                                                         object
What is your age?                                                                                                                        int32
What is your gender?                                                                                                                    object
What country do you live in?                                                                                                            object
year                                                                                                                                     int64
dtype: object

In [19]:
#changing age column to integer data type
Surveys_joined["What is your age?"] = Surveys_joined["What is your age?"].astype("int")

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3663919821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["What is your age?"] = Surveys_joined["What is your age?"].astype("int")

In [25]:
#Replacing possibly survey answer to maybe to keep values consitent 
Surveys_joined["Do you currently have a mental health disorder?"] = Surveys_joined["Do you currently have a mental health disorder?"].replace({"Possibly": "Maybe"})

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\1620414126.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Do you currently have a mental health disorder?"] = Surveys_joined["Do you currently have a mental health disorder?"].replace({"Possibly": "Maybe"})

In [26]:
Surveys_joined["Do you currently have a mental health disorder?"].value_counts()

Do you currently have a mental health disorder?
Yes           1358
No            1141
Maybe          711
Don't Know     182
Name: count, dtype: int64

In [31]:
Surveys_joined["If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?"].value_counts()

If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?
1-25%      183
26-50%     138
51-75%      56
76-100%     32
Name: count, dtype: int64

In [115]:
#Filling missing values with "Not applicable"
Surveys_joined["If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?"].fillna("Not applicable",inplace=True)

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3234924011.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Surveys_joined["If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?"].fillna("Not applicable",inplace=True)
C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3234924011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?"].fillna("Not applicable",inplace=True)

In [33]:
Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"].value_counts()

Do you believe your productivity is ever affected by a mental health issue?
Yes                     409
Unsure                   69
Not applicable to me     60
No                       34
Name: count, dtype: int64

In [40]:
len(Surveys_joined)

3392

In [59]:
#Replacing null values in the "Do you believe your productivity is ever affected by a mental health issue?" with No
#based on whether they have a mental health condition ie. they answered yes to the question if they have a mental health issue
Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"] = np.where((Surveys_joined["Do you currently have a mental health disorder?"] == "Yes") & (Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"].isna()), "No", Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"])

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\2886272320.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"] = np.where((Surveys_joined["Do you currently have a mental health disorder?"] == "Yes") & (Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"].isna()), "No", Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"])

In [61]:
#repalces values for the "Do you believe your productivity is ever affected by a mental health issue?" column with not applicable to me
#if they answered no ,maybe or dont know to if they have a mental health condition
Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"] = np.where((Surveys_joined["Do you currently have a mental health disorder?"] == "No") | (Surveys_joined["Do you currently have a mental health disorder?"] == "Maybe") | (Surveys_joined["Do you currently have a mental health disorder?"] == "Don't Know")  & (Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"].isna()), "Not applicable to me", Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"])

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\59788696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"] = np.where((Surveys_joined["Do you currently have a mental health disorder?"] == "No") | (Surveys_joined["Do you currently have a mental health disorder?"] == "Maybe") | (Surveys_joined["Do you currently have a mental health disorder?"] == "Don't Know")  & (Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"].isna()), "Not applicable to me", Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"])

In [63]:
Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"].isna().any()

False

In [64]:
#Validating previous steps
Surveys_joined["Do you believe your productivity is ever affected by a mental health issue?"].value_counts()

Do you believe your productivity is ever affected by a mental health issue?
Not applicable to me    2000
No                      1137
Yes                      233
Unsure                    22
Name: count, dtype: int64

In [67]:
Surveys_joined["Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?"].isna().sum()

572

In [68]:
Surveys_joined["Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?"].value_counts()

Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?
Yes      1047
Maybe     933
No        840
Name: count, dtype: int64

In [69]:
#Fillling na values with maybe
Surveys_joined["Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?"].fillna("Maybe", inplace=True)

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3601762537.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Surveys_joined["Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?"].fillna("Maybe", inplace=True)
C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3601762537.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?"].fillna("Maybe", inplace=True)

In [70]:
Surveys_joined["Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?"].value_counts()

Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?
Maybe    1505
Yes      1047
No        840
Name: count, dtype: int64

In [71]:
Surveys_joined["Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?"].isna().sum()

0

In [74]:
Surveys_joined["Does your employer offer resources to learn more about mental health disorders and options for seeking help?"].value_counts()

Does your employer offer resources to learn more about mental health disorders and options for seeking help?
No              1247
Yes              841
I don't know     732
Name: count, dtype: int64

In [75]:
#Replacing na values with "I don't know"
Surveys_joined["Does your employer offer resources to learn more about mental health disorders and options for seeking help?"].fillna("I don't know", inplace=True)

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\1777104236.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Surveys_joined["Does your employer offer resources to learn more about mental health disorders and options for seeking help?"].fillna("I don't know", inplace=True)
C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\1777104236.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Does your employer offer resources to learn more about mental health disorders and options for seeking help?"].fillna("I don't know", inplace=True)

In [76]:
Surveys_joined["Does your employer offer resources to learn more about mental health disorders and options for seeking help?"].isna().sum()

0

In [80]:
Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].isna().sum()

572

In [79]:
Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].value_counts()

Does your employer provide mental health benefits as part of healthcare coverage?
Yes                                1434
I don't know                        751
No                                  475
Not eligible for coverage / N/A      82
Not eligible for coverage / NA       78
Name: count, dtype: int64

In [81]:
#Replacing na values with "I don't know"
Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].fillna("I don't know", inplace=True)

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\1214091012.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].fillna("I don't know", inplace=True)
C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\1214091012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].fillna("I don't know", inplace=True)

In [84]:
#Reformatting answers to be consitent 
Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"] = Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].replace({"Not eligible for coverage / N/A" : "Not eligible for coverage", "Not eligible for coverage / NA" : "Not eligible for coverage"})

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\2656258069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"] = Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].replace({"Not eligible for coverage / N/A" : "Not eligible for coverage", "Not eligible for coverage / NA" : "Not eligible for coverage"})

In [85]:
Surveys_joined["Does your employer provide mental health benefits as part of healthcare coverage?"].value_counts()

Does your employer provide mental health benefits as part of healthcare coverage?
Yes                          1434
I don't know                 1323
No                            475
Not eligible for coverage     160
Name: count, dtype: int64

In [88]:
Surveys_joined["Is your employer primarily a tech company/organization?"].value_counts()

Is your employer primarily a tech company/organization?
1.0      1889
0.0       635
True      202
False      94
Name: count, dtype: int64

In [91]:
#Replacing 1/0 values and True/False values with yes or no
Surveys_joined["Is your employer primarily a tech company/organization?"] = Surveys_joined["Is your employer primarily a tech company/organization?"].replace({"1.0" : "Yes", "True" : "Yes", "0.0" : "No", "False" : "No" })

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3373508590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Is your employer primarily a tech company/organization?"] = Surveys_joined["Is your employer primarily a tech company/organization?"].replace({"1.0" : "Yes", "True" : "Yes", "0.0" : "No", "False" : "No" })

In [93]:
#REpalcing na values with "Don't Know"
Surveys_joined["Is your employer primarily a tech company/organization?"].fillna("Don't Know", inplace=True)

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3703462597.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Surveys_joined["Is your employer primarily a tech company/organization?"].fillna("Don't Know", inplace=True)
C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\3703462597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["Is your employer primarily a tech company/organization?"].fillna("Don't Know", inplace=True)

In [94]:
Surveys_joined["Is your employer primarily a tech company/organization?"].value_counts()

Is your employer primarily a tech company/organization?
Yes           2091
No             729
Don't Know     572
Name: count, dtype: int64

In [98]:
Surveys_joined["How many employees does your company or organization have?"].value_counts()

How many employees does your company or organization have?
More than 1000    773
100-500           676
26-100            614
6-25              435
500-1000          223
1-5                99
Name: count, dtype: int64

In [99]:

Surveys_joined["How many employees does your company or organization have?"].fillna("Unsure", inplace=True)

C:\Users\Brend\AppData\Local\Temp\ipykernel_4180\2836461943.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Surveys_joined["How many employees does your company or organization have?"].fillna("Unsure", inplace=True)

In [106]:
Surveys_joined.columns

Index(['Unnamed: 0',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
       'Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?',
       'Do you believe your productivity is ever affected by a mental health issue?',
       'If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?',
       'Do you currently have a mental health disorder?', 'What is your age?',
       'What is your gender?', 'What country do you live in?', 'year'],
      dtype='object')

In [113]:
Surveys_joined = Surveys_joined[columns_keep]

In [118]:
Surveys_joined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3392 entries, 0 to 3398
Data columns (total 12 columns):
 #   Column                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                --------------  -----
 0   How many employees does your company or organization have?                                                                            3392 non-null   object
 1   Is your employer primarily a tech company/organization?                                                                               3392 non-null   object
 2   Does your employer provide mental health benefits as part of healthcare coverage?                                                     3392 non-null   object
 3   Does your employer offer resources to learn more about mental health disorders and options for seeking help?                          3392 non-null   object
 4   Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?                                           3392 non-null   object
 5   Do you believe your productivity is ever affected by a mental health issue?                                                           3392 non-null   object
 6   If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?  3392 non-null   object
 7   Do you currently have a mental health disorder?                                                                                       3392 non-null   object
 8   What is your age?                                                                                                                     3392 non-null   int32
 9   What is your gender?                                                                                                                  3392 non-null   object
 10  What country do you live in?                                                                                                          3392 non-null   object
 11  year                                                                                                                                  3392 non-null   int64
dtypes: int32(1), int64(1), object(10)
memory usage: 460.3+ KB

In [120]:
Surveys_joined

,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Does your employer provide mental health benefits as part of healthcare coverage?,Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",Do you currently have a mental health disorder?,What is your age?,What is your gender?,What country do you live in?,year
0,26-100,Yes,Not eligible for coverage,No,Yes,Not applicable to me,Not applicable,No,39,Male,United Kingdom,2016
1,6-25,Yes,No,Yes,Yes,No,Not applicable,Yes,29,Male,United States of America,2016
2,6-25,Yes,No,No,Maybe,Not applicable to me,Not applicable,No,38,Male,United Kingdom,2016
3,Unsure,Don't Know,I don't know,I don't know,Maybe,Yes,1-25%,Yes,43,Male,United Kingdom,2016
4,6-25,No,Yes,No,No,No,Not applicable,Yes,43,Female,United States of America,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
3394,More than 1000,Yes,Yes,Yes,Yes,No,Not applicable,Yes,38,Male,United States of America,2022
3395,More than 1000,Yes,I don't know,Yes,Maybe,Not applicable to me,Not applicable,No,31,Female,Poland,2022
3396,26-100,Yes,Yes,Yes,No,Not applicable to me,Not applicable,Don't Know,40,Male,Australia,2022
3397,Unsure,Don't Know,I don't know,I don't know,Maybe,Not applicable to me,26-50%,Maybe,21,Female,Kazakhstan,2022
3398,6-25,Yes,No,No,No,No,Not applicable,Yes,32,Female,Russia,2022

In [119]:
Surveys_joined.to_csv("Survey_proc.csv")